Vagrant.configure(2) do |config|

    config.vm.define "node1" do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.network "private_network", ip: "10.0.0.10"
        node.vm.provider "virtualbox" do |vb|
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--memory", "256"]
        end
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.verbose = "vvv"
        end
    end

    config.vm.define "node2" do |node|
        node.vm.box = "bento/centos-7.1"
        node.vm.network "private_network", ip: "10.0.0.20"
        node.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--memory", "256"]
        end
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.verbose = "vvv"
        end
    end

end
