Vagrant.require_version ">= 1.7.4"

Vagrant.configure(2) do |config|

    config.vm.box = "williamyeh/ansible"
    config.vm.box_version = ">= 1.9.4.20151023"
    config.vm.hostname = "ANSIBLE"

    #config.vm.network "private_network", ip: "10.0.0.200"

    config.vm.synced_folder "..", "/vagrant"
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
    end

end
